name:                rt-haskell
version:             0.1.0.0
github:              "githubuser/rt-haskell"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rt-haskell#readme>

dependencies:
 - base >= 4.8.2.0
 - containers >= 0.5.6.2
 - random >= 1.1 
 - time >= 1.5.0 
 - stb-image >= 0.2.1
 - bitmap >= 0.0.2

library:
  source-dirs: src

executables:
  rt-haskell.out:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
      #- -fllvm -optlo-O3 -optl-ffast-math
      #- -fexcess-precision 
      #- -funfolding-use-threshold1000
    - -Wall
      #- -v2
    - -Werror
    - -O2
    - -prof
    - -fprof-auto
    - -funbox-strict-fields
    dependencies:
    - rt-haskell

tests:
  rt-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rt-haskell
